### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by seyidturgut** [georgetoloraia/SoloMinerBitcoin#1]
Bitcoin Miner started
00000000
Traceback (most recent call last):
  File "/Users/seyidturgut/Downloads/SoloMinerBitcoin-main/SoloMining.py", line 363, in thread_bitcoin_miner
    ret = bitcoin_miner_with_ai(self, model)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seyidturgut/Downloads/SoloMinerBitcoin-main/SoloMining.py", line 71, in bitcoin_miner_with_ai
    blockheader = bitcoin_miner(t, model)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seyidturgut/Downloads/SoloMinerBitcoin-main/SoloMining.py", line 290, in bitcoin_miner
    nNonce = get_random_nonce_from_file(nonce_file)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seyidturgut/Downloads/SoloMinerBitcoin-main/SoloMining.py", line 284, in get_random_nonce_from_file
    random_line = random.choice(lines)
                  ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/random.py", line 373, in choice
    raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence
00000000
Traceback (most recent call last):

**nonce.txt file is empty, how do I solve this?**

**Comment by georgetoloraia** [comment]
Hello..

# For solve `nonce.txt`
- Run: `python inportALLnonceFROMblockchain.py`

This code dump's all nonce from blcokchain... 
- but you need replace in code 33 line `end_height = 832290` to current height
